spring.application.name=pc-management-app
# PostgreSQL接続情報
spring.datasource.url=jdbc:postgresql://localhost:5432/pc_management_app
spring.datasource.username=postgres
spring.datasource.password=pass

# JPA関連設定
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
# or update, create-drop, validate